### ISSUE TITLE
I think I'd like to use this project

### ISSUE THREAD

**Issue by haldiggs** [arsalan/EmberJS.WebAPI#1]
but I'm not totally sure what its giving me. I currently use Ember in my MVC project. Do you have any demo work? or possibly a but more of an explaination as to what this project is giving me. The site front page looks great.

**Comment by arsalan** [comment]
@haldiggs This nuget is useful if you want to use Ember-Data out of the box with an ASP.NET Web API service that you wrote. It modifies the JSON as it leaves and enters the REST service to conform with the Json API standard that Ember-Data uses. 

If you don't need Ember-Data, you can ignore this nuget. Let me know how you have setup your Ember + MVC project. It will be interesting for me to take a look at it.

**Comment by haldiggs** [comment]
hmm, I've been using Ember to display my sites webapi data but hadn't noticed major issue. I do recall having to make sure it wasn't indented. Ember is pretty picky on the format. Maybe I should take look at what you've done here. Thanks
